Feature/spring security jwt login
code-challenge-hub/backend pull request #6
Opened 2024-07-01 14:04 UTC by haeunchoi-dev

Create Spring Security configuration with custom login and JWT filter

- Add Spring Security configuration 
- Add JWTUtil class for JWT token handling
- Add CustomFilter For Login and JWT
- Add enum UserRole for user roles

Update application.yml

- database configuration
- jpa configuration
- swagger-ui configuration
- jwt secret key
- API prefix

2024-07-20 05:04 UTC, KTG5672 requested changes
테스트 코드 작성 부탁 드립니다.

2024-07-20 05:04 UTC, KTG5672 commented on src/main/java/com/cch/codechallengehub/config/SecurityConfig.java
> +    public BCryptPasswordEncoder bCryptPasswordEncoder() {
구현체 보다는 인터페이스인 PasswordEncoderBean 등록 하는게 좀 더 수정하기 더 유연한 것으로 아는데 구현체로 등록한 이유가 뭔지 궁금합니다!

2024-07-20 05:04 UTC, KTG5672 commented on src/main/java/com/cch/codechallengehub/domain/User.java
> +	@Builder
생성자 마다 로직이 다르지 않은 것 같은데 가장 많은 파라미터를 받는 생성자로 빌더 하나만 만들어도 되지 않을까요?

2024-07-20 05:04 UTC, KTG5672 commented on src/main/java/com/cch/codechallengehub/filter/LoginFilter.java
> +        /*String email = null;
주석 말고 나중에 쓸거면 PR로 올려 놓읍시당

2024-08-18 06:09 UTC, haeunchoi-dev commented on src/main/java/com/cch/codechallengehub/config/SecurityConfig.java
> +    public BCryptPasswordEncoder bCryptPasswordEncoder() {
BCryptPasswordEncoder를 잘 바꾸지 않을것같아서 였는데, 구현체보단 인터페이스가 유연한것은 맞습니다. 수정하였습니다.

2024-08-18 06:09 UTC, haeunchoi-dev commented on src/main/java/com/cch/codechallengehub/domain/User.java
> +	@Builder
좋은지적 감사합니다. 수정하였습니다.

2024-08-18 06:09 UTC, haeunchoi-dev commented on src/main/java/com/cch/codechallengehub/filter/LoginFilter.java
> +        /*String email = null;
수정하였습니다.

2024-09-10 13:00 UTC, KTG5672 approved these changes
머지 해주세요

2024-09-10 13:44 UTC, merged